#!/bin/sh
DIR="$(dirname $0)"
if [ $# -ne 1 ]
then
# start screen and connect to it
screen -RmS server  $DIR/roomcontrolserver
else
# start screen detachted
screen -dmS server  $DIR/roomcontrolserver
fi