#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ $# -ne 1 ]
then
# start screen and connect to it
screen -RmS server  $DIR/roomcontrolserver
else
# start screen detachted
screen -dmS server  $DIR/roomcontrolserver
fi