/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p lirid_proxy org.lirid.receiver.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "lirid_proxy.h"

/*
 * Implementation of interface class OrgLiriDeviceInterface
 */

OrgLiriDeviceInterface::OrgLiriDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgLiriDeviceInterface::~OrgLiriDeviceInterface()
{
}

