cmake_minimum_required(VERSION 2.8.8)

#SET(CPACK_NSIS_INSTALLED_ICON_NAME "${CMAKE_CURRENT_SOURCE_DIR}/clients/roomeditor/images\\\\app.ico")
SET(CPACK_NSIS_MUI_ICON "${CPACK_NSIS_INSTALLED_ICON_NAME}")
SET(CPACK_NSIS_MUI_UNIICON "${CPACK_NSIS_INSTALLED_ICON_NAME}")
SET(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}")
SET(CPACK_NSIS_HELP_LINK "${CPACK_PROJECT_WEBURL}")
SET(CPACK_NSIS_URL_INFO_ABOUT "${CPACK_PROJECT_WEBURL}")
SET(CPACK_NSIS_MODIFY_PATH OFF)
# modify registry path after installation
add_subdirectory(tools/modify_registry_path)
SET(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
	ExecWait \\\"$INSTDIR\\\\bin\\\\modify_registry_path.exe install\\\"
	")
SET(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "
	ExecWait \\\"$INSTDIR\\\\bin\\\\modify_registry_path.exe uninstall\\\"
	")